Fixed the :mod:`trace` module CLI for Python source files with non-UTF-8
encoding.
